/** Chapter manifest — Book 1: The Second Self */
export const BOOK = {
  title: "The Second Self",
  subtitle: "Book 1 — The Signal Cycle",
  author: "Grappe501",
};

export const PARTS = [
  { id: "prologue", label: "Prologue" },
  { id: "part-i", label: "Part I — The Perfect World Cracks", chapters: [1, 12] },
  { id: "part-ii", label: "Part II — The Misdirect Machine", chapters: [13, 27] },
  { id: "part-iii", label: "Part III — The Veil", chapters: [28, 42] },
  { id: "part-iv", label: "Part IV — The Ghost", chapters: [43, 57] },
  { id: "part-v", label: "Part V — Convergence", chapters: [58, 71] },
  { id: "epilogue", label: "Epilogue", chapters: [72, 77] },
];

/** @type {Array<{id:string,num:number|null,title:string,pov:string,phase:string,phaseLabel:string,part:string,prose:boolean,draft?:string,publisher?:string,map?:string}>} */
export const CHAPTERS = [
  { id: "prologue", num: null, title: "The Martian Walk", pov: "Adrian Vale", phase: "v8", phaseLabel: "PRINT READY v8", part: "prologue", prose: true,
    publisher: "000_prologue_the_martian_walk_PUBLISHER.md" },
  { id: "ch-01", num: 1, title: "The Frozen Man", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "001_chapter_01_the_frozen_man_PUBLISHER.md" },
  { id: "ch-02", num: 2, title: "Running Double", pov: "Noah Vale", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "002_chapter_02_running_double_PUBLISHER.md" },
  { id: "ch-03", num: 3, title: "The Score", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "003_chapter_03_the_score_PUBLISHER.md" },
  { id: "ch-04", num: 4, title: "The City of Tomorrow", pov: "Dubai Artist", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "004_chapter_04_the_city_of_tomorrow_PUBLISHER.md" },
  { id: "ch-05", num: 5, title: "The Hero of Mars", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "005_chapter_05_the_hero_of_mars_PUBLISHER.md" },
  { id: "ch-06", num: 6, title: "The School of Everything", pov: "Noah Vale", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "006_chapter_06_the_school_of_everything_PUBLISHER.md" },
  { id: "ch-07", num: 7, title: "Mercer", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "007_chapter_07_mercer_PUBLISHER.md" },
  { id: "ch-08", num: 8, title: "The Empty Chair", pov: "Noah Vale", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "008_chapter_08_the_empty_chair_PUBLISHER.md" },
  { id: "ch-09", num: 9, title: "The Second Crime", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "009_chapter_09_the_second_crime_PUBLISHER.md" },
  { id: "ch-10", num: 10, title: "The Veiled City", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "010_chapter_10_the_veiled_city_PUBLISHER.md" },
  { id: "ch-11", num: 11, title: "The Third Question", pov: "Eli Mercer", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "011_chapter_11_the_third_question_PUBLISHER.md" },
  { id: "ch-12", num: 12, title: "Impossible", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-i", prose: true,
    publisher: "012_chapter_12_impossible_PUBLISHER.md" },
  { id: "ch-13", num: 13, title: "Memory of a Thing That Never Happened", pov: "Mara Voss", phase: "v8", phaseLabel: "PRINT READY v8", part: "part-ii", prose: true,
    publisher: "013_chapter_13_memory_of_a_thing_that_never_happened_PUBLISHER.md" },
  { id: "ch-14", num: 14, title: "The Storm", pov: "Noah Vale", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "014_chapter_14_the_storm.md" },
  { id: "ch-15", num: 15, title: "Signal Theory", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "015_chapter_15_signal_theory.md" },
  { id: "ch-16", num: 16, title: "Cass Ren", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "016_chapter_16_cass_ren.md" },
  { id: "ch-17", num: 17, title: "The City Under the City", pov: "Dubai Artist", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "017_chapter_17_the_city_under_the_city.md" },
  { id: "ch-18", num: 18, title: "The Third Signature", pov: "Eli Mercer", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "018_chapter_18_the_third_signature.md" },
  { id: "ch-19", num: 19, title: "The Book", pov: "Iona Vale", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "019_chapter_19_the_book.md" },
  { id: "ch-20", num: 20, title: "The Perfect Score", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "020_chapter_20_the_perfect_score.md" },
  { id: "ch-21", num: 21, title: "The Fire", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "021_chapter_21_the_fire.md" },
  { id: "ch-22", num: 22, title: "Vale's Last Interview", pov: "Archive", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "022_chapter_22_vales_last_interview.md" },
  { id: "ch-23", num: 23, title: "The Impossible Prediction", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "023_chapter_23_the_impossible_prediction.md" },
  { id: "ch-24", num: 24, title: "The Mirror", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "024_chapter_24_the_mirror.md" },
  { id: "ch-25", num: 25, title: "Mercer Exposed", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "025_chapter_25_mercer_exposed.md" },
  { id: "ch-26", num: 26, title: "The Disappearance", pov: "Eli Mercer", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "026_chapter_26_the_disappearance.md" },
  { id: "ch-27", num: 27, title: "The Fracture", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-ii", prose: false,
    map: "027_chapter_27_the_fracture.md" },
  { id: "ch-28", num: 28, title: "The Failure", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "028_chapter_28_the_failure.md" },
  { id: "ch-29", num: 29, title: "The Sound of the City", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "029_chapter_29_the_sound_of_the_city.md" },
  { id: "ch-30", num: 30, title: "Beautiful Things", pov: "Noah Vale", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "030_chapter_30_beautiful_things.md" },
  { id: "ch-31", num: 31, title: "The Real Dubai", pov: "Dubai Artist", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "031_chapter_31_the_real_dubai.md" },
  { id: "ch-32", num: 32, title: "The Fire Circle", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "032_chapter_32_the_fire_circle.md" },
  { id: "ch-33", num: 33, title: "The Children", pov: "Iona Vale", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "033_chapter_33_the_children.md" },
  { id: "ch-34", num: 34, title: "Signal Dreams", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "034_chapter_34_signal_dreams.md" },
  { id: "ch-35", num: 35, title: "The Ghost of Vale", pov: "Archive", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "035_chapter_35_the_ghost_of_vale.md" },
  { id: "ch-36", num: 36, title: "The Empty Church", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "036_chapter_36_the_empty_church.md" },
  { id: "ch-37", num: 37, title: "The Crack in Lena", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "037_chapter_37_the_crack_in_lena.md" },
  { id: "ch-38", num: 38, title: "The Impossible Children", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "038_chapter_38_the_impossible_children.md" },
  { id: "ch-39", num: 39, title: "The Other Self", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "039_chapter_39_the_other_self.md" },
  { id: "ch-40", num: 40, title: "The System Blinks", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "040_chapter_40_the_system_blinks.md" },
  { id: "ch-41", num: 41, title: "Mercer's Side", pov: "Eli Mercer", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "041_chapter_41_mercers_side.md" },
  { id: "ch-42", num: 42, title: "The Veil Choice", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iii", prose: false,
    map: "042_chapter_42_the_veil_choice.md" },
  { id: "ch-43", num: 43, title: "The Still One", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "043_chapter_43_the_still_one.md" },
  { id: "ch-44", num: 44, title: "The Broadcast", pov: "Noah Vale", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "044_chapter_44_the_broadcast.md" },
  { id: "ch-45", num: 45, title: "The Salt Report", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "045_chapter_45_the_salt_report.md" },
  { id: "ch-46", num: 46, title: "The City of Mirrors", pov: "Dubai Artist", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "046_chapter_46_the_city_of_mirrors.md" },
  { id: "ch-47", num: 47, title: "The Prediction Gap", pov: "Greenland Researcher", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "047_chapter_47_the_prediction_gap.md" },
  { id: "ch-48", num: 48, title: "The Empty Man", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "048_chapter_48_the_empty_man.md" },
  { id: "ch-49", num: 49, title: "The Dinner", pov: "Noah Vale", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "049_chapter_49_the_dinner.md" },
  { id: "ch-50", num: 50, title: "Lena's First Confession", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "050_chapter_50_lenas_first_confession.md" },
  { id: "ch-51", num: 51, title: "The Third Body", pov: "Eli Mercer", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "051_chapter_51_the_third_body.md" },
  { id: "ch-52", num: 52, title: "The Ghosts", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "052_chapter_52_the_ghosts.md" },
  { id: "ch-53", num: 53, title: "The Greenland Files", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "053_chapter_53_the_greenland_files.md" },
  { id: "ch-54", num: 54, title: "The Second War", pov: "Greenland Researcher", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "054_chapter_54_the_second_war.md" },
  { id: "ch-55", num: 55, title: "The Real Confession", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "055_chapter_55_the_real_confession.md" },
  { id: "ch-56", num: 56, title: "Mercer's Warning", pov: "Eli Mercer", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "056_chapter_56_mercers_warning.md" },
  { id: "ch-57", num: 57, title: "The Ghost in the System", pov: "Mara Voss", phase: "outline", phaseLabel: "Sequence Map · pre-prose", part: "part-iv", prose: false,
    map: "057_chapter_57_the_ghost_in_the_system.md" },
  { id: "ch-58", num: 58, title: "The First Fall", pov: "Dubai Artist", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "058_chapter_58_the_first_fall_PUBLISHER.md", map: "058_chapter_58_the_first_fall.md" },
  { id: "ch-59", num: 59, title: "Denial", pov: "Noah Vale", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "059_chapter_59_denial_PUBLISHER.md", map: "059_chapter_59_denial.md" },
  { id: "ch-60", num: 60, title: "The Salt Revelation", pov: "Mara Voss", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "060_chapter_60_the_salt_revelation_PUBLISHER.md", map: "060_chapter_60_the_salt_revelation.md" },
  { id: "ch-61", num: 61, title: "Static", pov: "Mara Voss", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "061_chapter_61_static_PUBLISHER.md", map: "061_chapter_61_static.md" },
  { id: "ch-62", num: 62, title: "The Empty Man Speaks", pov: "Adrian Vale", phase: "v6", phaseLabel: "PRINT READY v6", part: "part-v", prose: true,
    publisher: "062_chapter_62_the_empty_man_speaks_PUBLISHER.md", map: "062_chapter_62_the_empty_man_speaks.md" },
  { id: "ch-63", num: 63, title: "Greenland", pov: "Mara Voss", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "063_chapter_63_greenland_PUBLISHER.md", map: "063_chapter_63_greenland.md" },
  { id: "ch-64", num: 64, title: "The Architects", pov: "Lena Orra", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "064_chapter_64_the_architects_PUBLISHER.md", map: "064_chapter_64_the_architects.md" },
  { id: "ch-65", num: 65, title: "The Signal Chamber", pov: "Mara Voss", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "065_chapter_65_the_signal_chamber_PUBLISHER.md", map: "065_chapter_65_the_signal_chamber.md" },
  { id: "ch-66", num: 66, title: "The Blind Spot", pov: "Greenland Researcher", phase: "v6", phaseLabel: "PRINT READY v6", part: "part-v", prose: true,
    publisher: "066_chapter_66_the_blind_spot_PUBLISHER.md", map: "066_chapter_66_the_blind_spot.md" },
  { id: "ch-67", num: 67, title: "Mercer's Truth", pov: "Eli Mercer", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "067_chapter_67_mercers_truth_PUBLISHER.md", map: "067_chapter_67_mercers_truth.md" },
  { id: "ch-68", num: 68, title: "The Choice", pov: "Noah Vale", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "068_chapter_68_the_choice_PUBLISHER.md", map: "068_chapter_68_the_choice.md" },
  { id: "ch-69", num: 69, title: "The Second Self", pov: "Mara Voss", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "069_chapter_69_the_second_self_PUBLISHER.md", map: "069_chapter_69_the_second_self.md" },
  { id: "ch-70", num: 70, title: "Convergence", pov: "Mara Voss", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "070_chapter_70_convergence_PUBLISHER.md", map: "070_chapter_70_convergence.md" },
  { id: "ch-71", num: 71, title: "Disconnection", pov: "Mara Voss", phase: "v5", phaseLabel: "PRINT READY v5", part: "part-v", prose: true,
    publisher: "071_chapter_71_disconnection_PUBLISHER.md", map: "071_chapter_71_disconnection.md" },
  { id: "ch-72", num: 72, title: "The Release", pov: "Eli Mercer", phase: "v8", phaseLabel: "PRINT READY v8", part: "epilogue", prose: true,
    publisher: "072_chapter_72_the_release_PUBLISHER.md" },
  { id: "ch-73", num: 73, title: "False Peace", pov: "Noah Vale", phase: "v8", phaseLabel: "PRINT READY v8", part: "epilogue", prose: true,
    publisher: "073_chapter_73_false_peace_PUBLISHER.md" },
  { id: "ch-74", num: 74, title: "Breakfast", pov: "Noah Vale", phase: "v8", phaseLabel: "PRINT READY v8", part: "epilogue", prose: true,
    publisher: "074_chapter_74_breakfast_PUBLISHER.md" },
  { id: "ch-75", num: 75, title: "The Birth", pov: "Mira", phase: "v8", phaseLabel: "PRINT READY v8", part: "epilogue", prose: true,
    publisher: "075_chapter_75_the_birth_PUBLISHER.md" },
  { id: "ch-76", num: 76, title: "The Vault", pov: "Unknown Technician", phase: "v8", phaseLabel: "PRINT READY v8", part: "epilogue", prose: true,
    publisher: "076_chapter_76_the_vault_PUBLISHER.md" },
  { id: "ch-77", num: 77, title: "Connection Established", pov: "Unknown User", phase: "v8", phaseLabel: "PRINT READY v8", part: "epilogue", prose: true,
    publisher: "077_chapter_77_connection_established_PUBLISHER.md" },
];
